Fmd 48/host complete data extract
communitiesuk/funding-service-design-post-award-docker-runner pull request #13
Opened 2023-09-26 07:54 UTC by bobbi-hbrown

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?modal=detail&selectedIssue=SMD-191

Sets up localstack on the docker runner, creates two S3 buckets and transfers the two excel test files into them for local development.

### How to test
The Localstack service should be available by building and running the compose repo. It is available at port 4566.

2023-09-26 08:06 UTC, cyrusdobbs requested changes
Looks good

2023-09-26 08:06 UTC, cyrusdobbs commented on S3-files/example-total-grant-awarded.xlsx
Theses files looks fine for now. We'll want to make this particular one a fully mocked version of the real file later down the line so it's functional but that can be done in a separate ticket and PR.

2023-09-29 08:51 UTC, Connor-OS commented on .gitignore
> +/volume
Interested to know what is in this /volume directory? doesn't exist on my machine

2023-09-29 16:18 UTC, Connor-OS approved these changes
LGTM :)

2023-10-02 08:59 UTC, cyrusdobbs approved these changes

2023-10-02 09:01 UTC, merged